apiVersion: v2
name: pet-battle-tournament
description: A Helm chart for Kubernetes
type: application
version: gha-noc-test
appVersion: gha-noc-git-info
home: https://petbattle.github.io/helm-charts
maintainers:
- name: eformat
- name: noelo
