apiVersion: v2
name: pet-battle-tournament
description: A Helm chart for Kubernetes
type: application
version: 1.0.11
appVersion: 1.0.0
home: https://petbattle.github.io/helm-charts
maintainers:
- name: eformat
- name: noelo

