apiVersion: v2
name: pet-battle-tournament
description: Pet Battle Tournament
type: application
version: 1.0.39
appVersion: 1.0.0
home: https://petbattle.github.io/helm-charts
icon: https://avatars1.githubusercontent.com/u/68044996?s=200&v=4
maintainers:
- name: eformat
- name: noelo
dependencies:
  - name: pet-battle-infra
    version: "1.0.30"
    repository: "https://petbattle.github.io/helm-charts"
    import-values:
      - child: infinispan
        parent: infinispan
    tags:
      - infra
      - pet-battle-infra
