apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: pbrealm
  labels:
    realm: pbrealm
spec:
  realm:
    realm: "pbrealm"
    enabled: True
    displayName: "Pet Battle Single Sign onRealm"
  instanceSelector:
    matchLabels:
      app: pbkeycloak