apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: myuser
  labels:
    app: pbkeycloak
spec:
  user:
    username: "myuser"
    firstName: "John"
    lastName: "Doe"
    email: "myuser@keycloak.org"
    enabled: True
    credentials:
      - type: "password"
        value: "12345"
    clientRoles:
      "pbclient":
        - "users"
        - "viewer"
  realmSelector:
    matchLabels:
      realm: pbrealm