apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: pbadmin
  labels:
    app: pbkeycloak
spec:
  user:
    username: "pbadmin"
    firstName: "pbadmin"
    lastName: "pbadmin"
    email: "pbadmin@redhat.com"
    enabled: True
    credentials:
      - type: "password"
        value: "supersecret"
    realmRoles:
      - "admin"
    clientRoles:
      "pbclient":
        - "test"
        - "admin"
  realmSelector:
    matchLabels:
      realm: pbrealm