version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    hostname: mongo

  keycloak:
    image: quay.io/keycloak/keycloak:15.0.0
    ports:
      - "8080:8080"
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
