apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cert-utils-operator
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: cert-utils-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: cert-utils-operator.v0.2.2