{{- if .Values.infinispan.enabled }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: datagrid
spec:
  channel: 8.1.x
  installPlanApproval: Automatic
  name: datagrid
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: datagrid-operator.v8.1.1
---
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: infinispan
  labels:
        {{- include "pet-battle-tournament.labels" . | nindent 4 }}
spec:
  replicas: 1
  service:
    type: DataGrid
    sites:
      local:
        name: cloud
        expose:
          type: LoadBalancer
  security:
    endpointSecretName: connect-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: connect-secret
type: Opaque
stringData:
  identities.yaml: |-
    credentials:
    - username: developer
      password: password
    - username: operator
      password: password
---
apiVersion: v1
stringData:
  username: developer
  password: password
kind: Secret
metadata:
  name: infinispan-metrics-basic-auth
type: Opaque
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "pet-battle-tournament.labels" . | nindent 4 }}
  name: infinispan-monitoring
spec:
  endpoints:
    - targetPort: 11222
      path: /metrics
      honorLabels: true
      basicAuth:
        username:
          key: username
          name: infinispan-metrics-basic-auth
        password:
          key: password
          name: infinispan-metrics-basic-auth
      interval: 30s
      scrapeTimeout: 10s
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
        serverName: infinispan
  selector:
    matchLabels:
      clusterName: infinispan
{{- end }}
