{{- if and (eq .Values.grafana.enabled true) (eq .Values.keycloak.enabled true) (eq .Values.operatorgroup.enabled true) }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: pet-battle-tournament
spec:
  targetNamespaces:
    - {{ .Release.Namespace }}
{{- end }}
