---
apiVersion: v1
data:
  INFINISPAN_PASSWORD: cGFzc3dvcmQ=
  INFINISPAN_USER: ZGV2ZWxvcGVy
kind: Secret
metadata:
  name: {{ include "pet-battle-tournament.fullname" . }}-infinispan-auth
  labels:
    {{- include "pet-battle-tournament.labels" . | nindent 4 }}
type: Opaque
