{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pet-battle-tournament.fullname" . }}-monitor
  labels:
    {{- include "pet-battle-tournament.labels" . | nindent 4 }}
spec:
  endpoints:
  - interval: 30s
    port: tcp-8080
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/component: pet-battle-tournament

{{- if .Values.serviceMonitor.enableUserWorkloadMonitoring }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true
{{- end }}

{{- end }}