name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.7'
          architecture: x64
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Docker Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/main/resources/Dockerfile
          path: ${{ env.context }}
          registry: ${{ quay.io }}
          username: ${{ secrets.REPO_USER }}
          password: ${{ secrets.REPO_TOKEN }}
          repository: petbattle / pet-battle-tournament
          tag_with_ref: true
          tags: "GHABUILT"
