name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.7'
          architecture: x64
      - run: mvn -B package --file pom.xml
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.REPO_USER }}
          password: ${{ secrets.REPO_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/main/resources/Dockerfile
          repository: petbattle/pet-battle-tournament
          tags: quay.io/petbattle/pet-battle-tournament:ghabuilt
          cache-to: type=local,dest=cache
          cache-from: type=local,src=cache
